# The west manifest file (west.yml) for the Alif SDK.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# See the west documentation for more information:
# https://docs.zephyrproject.org/latest/develop/west/index.html

manifest:
  version: "0.13"

  defaults:
    remote: alif

  remotes:
    - name: alif
      url-base: https://github.com/alifsemi
    # Other repository sources:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: armmbed
      url-base: https://github.com/ARMmbed

  #
  # Please add items below based on alphabetical order
  projects:

    - name: zephyr
      repo-path: zephyr_alif
      revision: pull/371/head
      import:
        # In addition to the zephyr repository itself,
        # Alif SDK fetches the needed projects
        #
        # Please keep this list sorted alphabetically.
        name-allowlist:
          - canopennode
          - chre
          - edtt
          - fatfs
          - hal_alif
          - hal_ethos_u
          - liblc3
          - libmetal
          - littlefs
          - lvgl
          - lz4
          - mbedtls
          - mipi-sys-t
          - nanopb
          - net-tools
          - openthread
          - picolibc
          - psa-arch-tests
          - segger
          - tinycrypt
          - tf-m-tests
          - tflite-micro
          - TraceRecorderSource
          - uoscore-uedhoc
          - zcbor
          - zscilib
          - cmsis-dsp
    - name: matter
      repo-path: matter_alif
      revision: main
      path: modules/lib/matter

    - name: mcuboot_alif
      repo-path: mcuboot_alif
      path: bootloader/mcuboot
      revision: 346f7374ff4467e40b5594658f8ac67a5e9813c9

    - name: cmsis_alif
      revision: 85f6b92af0f6ac72594d391f895c45cc30847e41
      path: modules/hal/cmsis
      groups:
         - hal

    - name: dave2d
      repo-path: alif_dave2d-driver
      revision: 6bce53ec2563a72990b2b8bf3be08e8abdec5fd8
      path: modules/drivers/dave2d

    - name: aipl
      repo-path: alif_image-processing-lib
      revision: 1353536b04b2b6e6262e6044cfc6c75dbb7916d6
      path: modules/lib/aipl

  self:
    path: alif
    west-commands: scripts/west-commands.yml
